language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer update --prefer-source --dev
  - composer self-update

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/clover.xml
  - php build/coverage-checker.php build/clover.xml 55